
import { Inter } from "next/font/google";
import "./globals.css";

import Main from './Main';
import { ThemeProvider } from "./context/ThemeContext";

import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio 55",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Main>
            <Navbar />
            {children}
            <Footer />
          </Main>
        </ThemeProvider>
      </body>
    </html>
  );
}
